<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE payments[
  <!ELEMENT payments (payment+)>
  <!ELEMENT payment (datePayment, userID, amount, cardNo, expiry, cvv)>  
  <!ELEMENT datePayment (#PCDATA)>
  <!ELEMENT userID (#PCDATA)>
  <!ELEMENT amount (#PCDATA)>
  <!ELEMENT cardNo (#PCDATA)  >
  <!ELEMENT expiry (#PCDATA)>
  <!ELEMENT cvv (#PCDATA)>
  

]>
<payments>
  <payment>
    <datePayment>21/9/2018 11:54:26 AM</datePayment>
    <userID>1</userID>
    <amount>1200.00</amount>
    <cardNo>1267891187337790</cardNo>
    <expiry>11/22</expiry>
    <cvv>123</cvv>
  </payment>
  <payment>
    <datePayment>10/1/2019 2:01:13 PM</datePayment>
    <userID>2</userID>
    <amount>4.00</amount>
    <cardNo>1111111112</cardNo>
    <expiry>11/2022</expiry>
    <cvv>112</cvv>
  </payment>
  <payment>
    <datePayment>10/1/2019 2:06:43 PM</datePayment>
    <userID>2</userID>
    <amount>4.00</amount>
    <cardNo>1124355323</cardNo>
    <expiry>11/2022</expiry>
    <cvv>112</cvv>
  </payment>
  <payment>
    <datePayment>10/1/2019 3:16:35 PM</datePayment>
    <userID>9</userID>
    <amount>20.00</amount>
    <cardNo>2334443</cardNo>
    <expiry>11/2022</expiry>
    <cvv>123</cvv>
  </payment>
</payments>